# Generated by Django 5.1.2 on 2024-10-21 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reminder'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Title'),
        ),
    ]
